# Generated by Django 4.2.14 on 2024-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "ADMIN"), (2, "TEACHER"), (3, "STUDENT")],
                default=3,
                max_length=50,
            ),
        ),
    ]
