# Generated by Django 4.2.14 on 2024-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0007_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
